"""Unofficial AHL SDK. Research dependencies load only when requested."""

from importlib import import_module

from ahl_api.client import (
    AHL,
    AhlClient,
    AhlError,
    AhlClientError,
    AuthenticationError,
    SessionExpiredError,
    TransportError,
    RiskCheckError,
    BrokerRejectedError,
    NotSupported,
    AhlSession,
    read_dotenv,
)

__version__ = "0.3.0"

_OPTIONAL_EXPORTS = {
    "BacktestConfig": "ahl_api.backtest",
    "BacktestEngine": "ahl_api.backtest",
    "BacktestResult": "ahl_api.backtest",
    "Fill": "ahl_api.backtest",
    "Order": "ahl_api.backtest",
    "OrderStrategy": "ahl_api.backtest",
    "Position": "ahl_api.backtest",
    "StrategyContext": "ahl_api.backtest",
    "SweepResult": "ahl_api.backtest",
    "SweepRun": "ahl_api.backtest",
    "TargetWeightStrategy": "ahl_api.backtest",
    "calculate_trade_cost": "ahl_api.backtest",
    "load_historical_data": "ahl_api.backtest",
    "normalize_bars": "ahl_api.backtest",
    "run_parameter_sweep": "ahl_api.backtest",
    "write_backtest_report": "ahl_api.backtest",
    "write_sweep_report": "ahl_api.backtest",
    "LiquidityFilteredMomentumStrategy": "ahl_api.strategies",
    "MomentumTrendFilterStrategy": "ahl_api.strategies",
    "PullbackDcaStrategy": "ahl_api.strategies",
    "RankedSymbol": "ahl_api.strategies",
    "average_traded_value": "ahl_api.strategies",
    "ema": "ahl_api.strategies",
    "rank_momentum_universe": "ahl_api.strategies",
    "rate_of_change": "ahl_api.strategies",
    "sma": "ahl_api.strategies",
    "DataAuditResult": "ahl_api.research",
    "DataProvenance": "ahl_api.research",
    "MembershipSchedule": "ahl_api.research",
    "StrategySpec": "ahl_api.research",
    "StressScenario": "ahl_api.research",
    "WalkForwardConfig": "ahl_api.research",
    "WalkForwardResult": "ahl_api.research",
    "audit_market_data": "ahl_api.research",
    "default_stress_scenarios": "ahl_api.research",
    "generate_walk_forward_folds": "ahl_api.research",
    "price_index_benchmark": "ahl_api.research",
    "run_walk_forward_validation": "ahl_api.research",
    "BollingerTrendReversionStrategy": "ahl_api.research_strategies",
    "CloseChannelBreakoutStrategy": "ahl_api.research_strategies",
    "CrossSectionalMomentumStrategy": "ahl_api.research_strategies",
    "DataUnavailableError": "ahl_api.research_strategies",
    "RsiTrendPullbackStrategy": "ahl_api.research_strategies",
    "TechnicalCandidate": "ahl_api.research_strategies",
    "TechnicalEnsembleStrategy": "ahl_api.research_strategies",
    "annualized_close_volatility": "ahl_api.research_strategies",
    "lagged_return": "ahl_api.research_strategies",
    "median_traded_value": "ahl_api.research_strategies",
    "require_high_low": "ahl_api.research_strategies",
    "rsi": "ahl_api.research_strategies",
}
__all__ = [
    "AHL",
    "AhlClient",
    "AhlError",
    "AhlClientError",
    "AuthenticationError",
    "SessionExpiredError",
    "TransportError",
    "RiskCheckError",
    "BrokerRejectedError",
    "NotSupported",
    "AhlSession",
    "read_dotenv",
    "BacktestConfig",
    "BacktestEngine",
    "BacktestResult",
    "Fill",
    "Order",
    "OrderStrategy",
    "Position",
    "StrategyContext",
    "SweepResult",
    "SweepRun",
    "TargetWeightStrategy",
    "calculate_trade_cost",
    "load_historical_data",
    "normalize_bars",
    "run_parameter_sweep",
    "write_backtest_report",
    "write_sweep_report",
    "LiquidityFilteredMomentumStrategy",
    "MomentumTrendFilterStrategy",
    "PullbackDcaStrategy",
    "RankedSymbol",
    "average_traded_value",
    "ema",
    "rank_momentum_universe",
    "rate_of_change",
    "sma",
    "DataAuditResult",
    "DataProvenance",
    "MembershipSchedule",
    "StrategySpec",
    "StressScenario",
    "WalkForwardConfig",
    "WalkForwardResult",
    "audit_market_data",
    "default_stress_scenarios",
    "generate_walk_forward_folds",
    "price_index_benchmark",
    "run_walk_forward_validation",
    "BollingerTrendReversionStrategy",
    "CloseChannelBreakoutStrategy",
    "CrossSectionalMomentumStrategy",
    "DataUnavailableError",
    "RsiTrendPullbackStrategy",
    "TechnicalCandidate",
    "TechnicalEnsembleStrategy",
    "annualized_close_volatility",
    "lagged_return",
    "median_traded_value",
    "require_high_low",
    "rsi",
]


def __getattr__(name):
    module = _OPTIONAL_EXPORTS.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    try:
        value = getattr(import_module(module), name)
    except ModuleNotFoundError as exc:
        if exc.name in {"pandas", "numpy", "matplotlib"}:
            raise ImportError("Install research support with: pip install 'ahl-api[research]'") from exc
        raise
    globals()[name] = value
    return value
